### PR TITLE
Update logback, netty, caffeine, slf4j and surefire

### PR DESCRIPTION
**Pull request by no2chem**
This PR updates the versions of various components to their
latest versions.

### CODE REVIEW

**Comment by no2chem** [comment]
mapsAsMqsTest has been intermittently failing for awhile. Perhaps a fix would be to disable these faulty tests on Travis for the time being.

**Comment by dahliamalkhi** [comment]
note that useMapsAsMQs test has (a) surfaced important issues in the past, and (b) tries to emulate MP use case.

**Comment by no2chem** [comment]
@dahliamalkhi It's not a particularly useful test if we can't tell if the failures are due to a bug in the test or the code. Either way it seems that @slfritchie may have fixed the test, could you please check his PR?

**Comment by slfritchie** [comment]
It's PR #783, which fixes the bug described by #780, "useMapsAsMQs fails intermittently".

**Pull request merged**
