### PR TITLE
Reproduce intermittent failure on travis

### PR DESCRIPTION
**Pull request by zalokhan**
Trying to reproduce an intermittently failing test on Travis.
testSequencerFailure in ManagementViewTest

### CODE REVIEW

**Comment by no2chem** [comment]
@slfritchie I think you didn't mean to also approve the PR

**Comment by zalokhan** [comment]
@slfritchie Very rare. Ive seen it once and Maithem has seen it once or twice.

```

invokeFailureHandler                                        [PASS]
testSequencerFailover                                       [FAIL - ComparisonFailure:L444]
sequencerFailoverBackpointerCheck                           [PASS]
removeSingleNodeFailure                                     [PASS]
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 49.477 sec <<< FAILURE! - in org.corfudb.runtime.view.ManagementViewTest
testSequencerFailover(org.corfudb.runtime.view.ManagementViewTest)  Time elapsed: 6.095 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...nresponsiveServers=[[test:1], epoch=2])> but was:<...nresponsiveServers=[[], epoch=3])>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.corfudb.runtime.view.ManagementViewTest.testSequencerFailover(ManagementViewTest.java:444)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.corfudb.AbstractCorfuTest$1$1.evaluate(AbstractCorfuTest.java:89)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)


Failed tests: 
  ManagementViewTest.testSequencerFailover:444 expected:<...nresponsiveServers=[[test:1], epoch=2])> but was:<...nresponsiveServers=[[], epoch=3])>
Tests run: 294, Failures: 1, Errors: 0, Skipped: 2
```

**Comment by slfritchie** [comment]
I assumed that Zeeshan wanted to see the output on possibly many runs going forward.  I can live with the spam for the sake of HeisenBug Hunting.  If Zeeshan is planning on pressing whatever "re-run" button at Travis-CI to re-execute tests for this branch, that's fine too ... this branch wouldn't be merged.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **aff8530**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #595 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/hbkRQoCAYMiPvy0T3Pxlp7Uh34thSDVK)

**Comment by zalokhan** [comment]
Unable to reproduce the failure.
Closing this.

**Pull request closed without merging**
