### PR TITLE
Implement precise abort support

### PR DESCRIPTION
**Pull request by no2chem**
This patch introduces precise aborts. When precise aborts are turned on, the 
runtime will check if a conflict aborted by the sequencer is a false conflict.

The sequencer has been patched to provide the address of the conflict and
the stream that caused the abort,  and now has an additional mechanism for
retrying "validated" streams. The conflict extractor from #493 has been
brought back, and allows the runtime to determine the original conflict objects
from the SMR entry.

In the sequencer server, handleTxToken checks for conflicts as before. 
TxResolutionInfo now contains a map of "validated streams", which are
streams the client has manually scanned for conflicts. During the scan
of each conflicting stream, if there is a conflict, the sequencer consults with
the validated stream map first. If the stream is in the validated stream map
and the address of the validation is greater than or equal to the current tail
for the conflict key, the Tx is accepted (as before). Otherwise, the Tx is
rejected, and the tail (the address of the conflict) and the stream ID is returned,
in addition to any previous information.

The runtime uses this information to manually scan for conflicts. When a conflict
is detected, it scans the conflicting stream starting from the snapshot address
to the conflict address. The runtime extracts the original conflict objects from
the entry and does a full equality check. If there are no true conflicts, then
we retry with the sequencer, submitting the addresses and streams that were
scanned. If there are true conflicts, the transaction aborts as normal. The client
will retry until there is a true conflict, or it encounters a trim exception while
scanning, which it will then abort with a cause of trimmed.

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **3000264**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #821 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/CYQY4WzIUFGPAfVen7dxrn6dV33z5S9b)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **c93cd83**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #821 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/4ZBlB7nP3K59TqM4SPeulf0QYgyN9cPZ)

**Comment by no2chem** [comment]
This PR closes #753 by providing a mechanism to avoid false conflicts.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **d41de2e**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #821 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/EBfbiXRAtWWzZQmV7d9DaXHpDXlz4GSF)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **3be8384**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #821 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/THGGzDKIQ89Si4XCMrN3k5TVeyni7af4)

**Pull request merged**
