### PR TITLE
Workload Generator

### PR DESCRIPTION
**Pull request by Maithem**
Added a new module for the workload generator. The generator
implements different data distributions that can be sampled.

### CODE REVIEW

**Comment by Maithem** [comment]
@slfritchie This PR needs more clean up, but preliminary feedback is welcome.

**Comment by Maithem** [comment]
A uniform distribution is used for sampling for now, but I will change it later, a zipf'n distribution might be more realistic.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **f903d0b**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #835 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/M6eEhbe8aDQ66Ukn2sstnaThkCJnkc0W)

**Comment by Maithem** [comment]
squashing this into #838

**Pull request closed without merging**
