### PR TITLE
Implement AutoCloseableByteBuf, a wrapper around bytebuf which uses the autocloseable interface

### PR DESCRIPTION
**Pull request by no2chem**
An autocloseablebytebuf implements AutoClosable, which will release a ByteBuf when it exits a try-catch block.

---
This change is [Reviewable](https://reviewable.io/reviews/corfudb/corfudb/109)

### CODE REVIEW

**Comment by medhavidhawan** [comment]
*[src/main/java/org/corfudb/runtime/view/ChainReplicationView.java, line 65 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/109#-KD4HZ1v-19cPfp-LIZQ:-KD4HZ1v-19cPfp-LIZR:476858363) ([raw file](https://github.com/corfudb/corfudb/blob/880d5c6390c2300a41cddadde7d5e8ffcc947ed2/src/main/java/org/corfudb/runtime/view/ChainReplicationView.java#L65)):*
Great that is the correct solution.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/109)*

**Comment by medhavidhawan** [comment]
*[src/main/java/org/corfudb/util/AutoCloseableByteBuf.java, line 33 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/109#-KD4KXaW57nW4WtX2gZD:-KD4KXaW57nW4WtX2gZE:-1438126491) ([raw file](https://github.com/corfudb/corfudb/blob/880d5c6390c2300a41cddadde7d5e8ffcc947ed2/src/main/java/org/corfudb/util/AutoCloseableByteBuf.java#L33)):*
Do you need to override everything ? Why use a decorator pattern. Can we not do simple inheritence

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/109)*

**Comment by medhavidhawan** [comment]
*[src/main/java/org/corfudb/util/AutoCloseableByteBuf.java, line 30 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/109#-KD4KigbhI5LTxYXThUH:-KD4KigcFbSE0k6ECofk:2120937429) ([raw file](https://github.com/corfudb/corfudb/blob/880d5c6390c2300a41cddadde7d5e8ffcc947ed2/src/main/java/org/corfudb/util/AutoCloseableByteBuf.java#L30)):*
is it not possible to call this.release() or super.release() and not bother with the ByteBuf variable.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/109)*

**Comment by no2chem** [comment]
*[src/main/java/org/corfudb/util/AutoCloseableByteBuf.java, line 33 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/109#-KD4KXaW57nW4WtX2gZD:-KD4LtkL3Rnb-UOIJgM6:-1409372798) ([raw file](https://github.com/corfudb/corfudb/blob/880d5c6390c2300a41cddadde7d5e8ffcc947ed2/src/main/java/org/corfudb/util/AutoCloseableByteBuf.java#L33)):*
This... is a decorator pattern. In Java, Override is a compile-time annotation which simply ensures that the signature of the method matches that of a superclass method.. No we can't do simple inheritance because ByteBuf is abstract, how would you inherit an object of an unknown dervied class at runtime?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/109)*

**Comment by no2chem** [comment]
*[src/main/java/org/corfudb/util/AutoCloseableByteBuf.java, line 30 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/109#-KD4KigbhI5LTxYXThUH:-KD4LCSwYLU7FtNNEjmh:-1805716218) ([raw file](https://github.com/corfudb/corfudb/blob/880d5c6390c2300a41cddadde7d5e8ffcc947ed2/src/main/java/org/corfudb/util/AutoCloseableByteBuf.java#L30)):*
Well, the bytebuf variable is used by all the other decorated functions, so calling buf maintains consistency and protects against accidental recursion

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/109)*

**Comment by medhavidhawan** [comment]
*[src/main/java/org/corfudb/util/AutoCloseableByteBuf.java, line 33 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/109#-KD4KXaW57nW4WtX2gZD:-KD4NHFoI7fDIiUdfxGH:-872076830) ([raw file](https://github.com/corfudb/corfudb/blob/880d5c6390c2300a41cddadde7d5e8ffcc947ed2/src/main/java/org/corfudb/util/AutoCloseableByteBuf.java#L33)):*
Cool got it. I was just hoping we do not have to write this extra boiler plate. try the unknown derived class thing, but if it messes up the thinking process, let it be.  In any case this is a good solution, maybe a bit more verbose.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/109)*

**Comment by no2chem** [comment]
*[src/main/java/org/corfudb/util/AutoCloseableByteBuf.java, line 33 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/109#-KD4KXaW57nW4WtX2gZD:-KD4O2jlAEXl15Jro-xy:-733767587) ([raw file](https://github.com/corfudb/corfudb/blob/880d5c6390c2300a41cddadde7d5e8ffcc947ed2/src/main/java/org/corfudb/util/AutoCloseableByteBuf.java#L33)):*
Yeah, it's a bit unfortunate. Maybe with some dynamic type generation there'd be a way, but let's leave it at this for now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/109)*

**Pull request merged**
