### PR TITLE
More ckpoint tests

### PR DESCRIPTION
**Pull request by dahliamalkhi**
merging master and adding a test class

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **32e4cb7**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #651 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/H7i4emmxlxAhnCVoCXd9e7vzQDg2BQgO)

**Comment by slfritchie** [comment]
Hi, Dahlia.  If I merge this, I'd cherry-pick only the CheckpointTest class from 32e4cb7ca8815a70ae3cb13cd1284dd8253d5a66.

That commit also contains a change to StreamsView.java that appears to be new?  It doesn't look like it came from the `master` branch merge, but I'm not sure.  It does not appear necessary to make the new CheckpointTest test cases pass, so I'm puzzled.

**Comment by dahliamalkhi** [comment]
this is a bug fix from #646 , which has been merged into master. Checkpointing surfaced this bug: It is the first serious workload we have which writes entries into the log with empty conflict-parameters. As soon as hole fillingTrigered a retry, it caused a null pointer exception.

**Comment by slfritchie** [comment]
The structure of the new tests are fairly similar internally.  If I had more time, I'd be tempted to refactor them now.  But I'll wait, sorry, and just steal the CheckpointTest class and add it to #641.  Many thanks for the extra test cases.

**Comment by dahliamalkhi** [comment]
agreed. I had the same sentiment.

**Pull request closed without merging**
