### PR TITLE
Client quorum support completed under the new replication API

### PR DESCRIPTION
**Pull request by kspirov**

### CODE REVIEW

**Comment by kspirov** [comment]
@no2chem  I believe I am using the new API in a correct manner. 
BTW there is one bug I found during the test, it is true for the chain replication too (not quorum specific). You are able to read a log position higher than the tail of the log in the sequencer, and it becomes a HOLE. Before you would receive EMPTY.  See QuorumReplicationProtocolAdditionalTests:183. I don't know is it dangerous change of the contract or not, probably you just need to check on higher levels?

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **be105c2**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #551 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/es1YhXVjxYxu78wtETSFJshQvMLwd0vj)

**Comment by dahliamalkhi** [comment]
HOLE fill on reading beyond the tail: I think it is fine. There is no reason for the runtime to ever do this.

**Comment by no2chem** [comment]
Yeah, sorry for the late comment on this, but I don't think it's a correctness issue, just potentially a performance issue. We could make hole filling require a "permit"/token from the sequencer as well but it seems somewhat overkill.

**Comment by kspirov** [comment]
I also believe it's OK. So we are  ready to merge?

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **3c5af39**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #551 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/Z7Rud6l1NPncPfyfSy4ywfBE2hpoV4pl)

**Comment by kspirov** [comment]
I see conflict due to delayed merge. I will resolve them.

**Comment by no2chem** [comment]
Yes, sorry about the holdup. We'll merge you in as soon as you rebase, unless @dahliamalkhi has any objections



On Thu, May 04, 2017 at 9:08am, Konstantin Spirov < notifications@github.com [notifications@github.com] > wrote:
I see conflict due to delayed merge. I will resolve them.

**Comment by kspirov** [comment]
Rebased on a top to single commit in order not to pollute the log too much. 
Please wait Travis first.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **76fd10e**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Memory mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #551 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/MTMnOrZ323wcgsB5KiQu25UWVK4Ssb1j)

**Pull request merged**
