### PR TITLE
Removed .deb and other binaries

### PR DESCRIPTION
**Pull request by Maithem**
Unfortunately, the only way to prune these binaries is to re-write the git history.

### CODE REVIEW

**Comment by Maithem** [comment]
Files deleted:

0cbce0cf6493c446252fd19fe991a229abd70f2d 9190315 cassandra-binding-0.1.4.jar
2f4e29b65ed80090b7eaa380102b8cc9fc91e1da 8569156 corfu-0.1-721.deb
b2b125a3f4b5b2d6aef494fa7082d8dc286b8210 29050808 corfu-server_0.1+1001_all.deb
552d3f9f99d111b56edef962741e4353f816d0e8 29053890 corfu-server_0.1+1004_all.deb
fafea1ff55b76579dc7c480935b8464ed5a3f308 29055606 corfu-server_0.1+1010_all.deb
9b19dd44ed28877a8d87f4100038ffe87609d2c3 29055740 corfu-server_0.1+1016_all.deb
1f4395d8d031fed49b50e5d742a42cfd2c644be3 29068648 corfu-server_0.1+1037_all.deb
f62a94325c9b55e278953e12d0cf279c67d39bc8 29069722 corfu-server_0.1+1040_all.deb
a7a806a010479c89d978e6cda3022ed4e15af3b6 29069766 corfu-server_0.1+1045_all.deb
0d98dbb946463181ef2c20ff5946ab7a43121402 29069744 corfu-server_0.1+1048_all.deb
30c1ad16e7b1b75b8644db75a757231fd6abd0a3 29077022 corfu-server_0.1+1053_all.deb
0143339232cc5040b5038a5be05200368551054c 29082076 corfu-server_0.1+1055_all.deb
a425dcbca9eb97e381fa5b772b75c14f40ef80be 29083762 corfu-server_0.1+1066_all.deb
a42f9c549626dac3868889388743bd0f1955a5cd 29083966 corfu-server_0.1+1078_all.deb
67b5881bf96e802ad943764b69554d3fe305fd7d 29208284 corfu-server_0.1+1099_all.deb
afac6af16930468e9817222d887efa4a16db41aa 29084136 corfu-server_0.1+1114_all.deb
11fff0562401c09706fecc737b9b45558e222a0d 9969228 corfu-server_0.1+1119_all.deb
f35ce544f3846d4a6c341b20ca0497cd449a187c 11301394 corfu-server_0.1+1122_all.deb
f0cfdb0942d218146f658212c08f179a9f0ec739 11653416 corfu-server_0.1+1123_all.deb
86e67cb40ac81200ca382026d32cb1f6a7f33ba9 11653504 corfu-server_0.1+1127_all.deb
0c61e40b3e864b6c31f9bc73f4267972cc6bb122 11653554 corfu-server_0.1+1138_all.deb
563c11af7c5006a58041286536753d7137d5a897 11655796 corfu-server_0.1+1145_all.deb
033aaf15c3ef0e4ff0b0d6cf676419145ab82d07 11659402 corfu-server_0.1+1151_all.deb
8604351783d9b9a0f1cfa098f87a1a8322db7a76 16255016 corfu-server_0.1+1174_all.deb
8ef61d9801bb4a57a249bb5f23ec9300efd3485a 16250992 corfu-server_0.1+1175_all.deb
8e2abca596a9558d7c90b874498b8a7e7bc48826 8568762 corfu-server_0.1+716_all.deb
c57ee9d9281f5c0042ed671e8e198ecbc1a61a7a 8569218 corfu-server_0.1+721_all.deb
1c3f5fe010ae60a8531e2f9617ef556213ac29fe 8570284 corfu-server_0.1+728_all.deb
77df8e0f9dde16e746feb684c8eb160c40853c41 8574606 corfu-server_0.1+745_all.deb
918982a9cfd317869084a957b3310a410ef07b80 8574640 corfu-server_0.1+748_all.deb
2780205085ef42376c6441b5f122d9e3f77775f8 8577782 corfu-server_0.1+751_all.deb
a37cbf5054ad8fc5ed28971a7a802d11c9bd7826 8580264 corfu-server_0.1+754_all.deb
708d3de48028da7fbb29bb424016917885887263 8664688 corfu-server_0.1+763_all.deb
a621287ab9e1b0aad132d0ab7eb4968607990388 8665578 corfu-server_0.1+769_all.deb
48cca1c3e314bbde8198f8e61a1583f845d89eab 8666450 corfu-server_0.1+775_all.deb
2d982bba88d14a8834cf4848e7ba85c46e33ba23 8667404 corfu-server_0.1+778_all.deb
daceb4479f353f231239c32b535a51acb2d35d91 8667302 corfu-server_0.1+781_all.deb
e5643a016e13c113fb41860237e5b43389de7e76 8912078 corfu-server_0.1+784_all.deb
116f613598bcbb4c0a719353953a1fb84926f235 8928922 corfu-server_0.1+788_all.deb
90ed128f6368a19a798c4ef315a9d68660999c66 8941870 corfu-server_0.1+793_all.deb
4a03f7c61e5714ea08bad9dcd6c59b1960c46cc0 8943724 corfu-server_0.1+796_all.deb
b8fc21a2b0dcb2cdd5bcfef57aa9c8170efaf4b2 8952232 corfu-server_0.1+801_all.deb
15e7fba4f464661ab9b073d71e4b67feebd1915f 8962346 corfu-server_0.1+808_all.deb
5946d2c959ce297d829bc0d92061cd6f8caab35d 8962374 corfu-server_0.1+811_all.deb
e49d4195173eeea61208d16b9ca01883687aa48c 8962040 corfu-server_0.1+814_all.deb
5e8313ba07cf8d78f4327749c8ee5dbac213c95d 9943336 corfu-server_0.1+817_all.deb
6e32a9764c5bbd4b8de1a5ef653e49b1f60f879e 9943766 corfu-server_0.1+820_all.deb
6e5aac0688a217cd7b1a8b68b178743282773f63 9944218 corfu-server_0.1+823_all.deb
fbeee8dc30088620dbdc1b04da4daac90522a4d1 9944540 corfu-server_0.1+826_all.deb
7398fa5c5e9ae1b7fa90bacd6bc45c7ea8a1763e 9944318 corfu-server_0.1+829_all.deb
73d5113f29fb18eda4dde74f5026dff2a499eec0 9949114 corfu-server_0.1+832_all.deb
c29dd6b56ac8cc1471bc65aea6b91df3ff0d21e4 9949364 corfu-server_0.1+835_all.deb
aa7f119037dc69a9d6599d6efd609e2cfe073bf2 9949808 corfu-server_0.1+838_all.deb
eb686f10009ccf9a9dfb9b0bb717efaacf54278f 9949982 corfu-server_0.1+842_all.deb
d35131d2840d4025c6c95b83302c5b78a77d60dd 10048414 corfu-server_0.1+845_all.deb
b971f0c0fd950b3e742dfcbcfdfbd98ff485842e 10048698 corfu-server_0.1+848_all.deb
19a61ecd2e08b01066864c33aede42dbc7404523 10049454 corfu-server_0.1+851_all.deb
5c657c2f570ec30968af8cdad65bedc06248f1ae 10049436 corfu-server_0.1+856_all.deb
66b69f8a978a5ad23bc273e02039c1b1b36a4f10 10053478 corfu-server_0.1+863_all.deb
4a776867c0d82f22e829c19b0a9482f72f39f485 10053438 corfu-server_0.1+867_all.deb
151b44e30a6b7788899fbf431191a0d20c29e927 10048886 corfu-server_0.1+872_all.deb
c2251d37d3b656da3e319b1841c6291887db0647 10054102 corfu-server_0.1+877_all.deb
a5b09ad94f4a3e372c8e0591d9248c5835634886 10054250 corfu-server_0.1+882_all.deb
8524e5213289201b1eb9e6f5f0026e9cd9006330 10054652 corfu-server_0.1+885_all.deb
72421854b58b9dbe4a2b5a0a45248ac5d78476b8 10057210 corfu-server_0.1+888_all.deb
854b7320ff6e653c4f125b620bb3fc6f7cbe9c97 10098870 corfu-server_0.1+891_all.deb
bbef1e616345bd88832085d26cc9405daf4d1b72 28855418 corfu-server_0.1+896_all.deb
040614af82b3c39234718f41a3354485bd055c67 28855326 corfu-server_0.1+902_all.deb
c80a5290f9b0c5192dcd701f6ddbebfd5c93c246 28855252 corfu-server_0.1+907_all.deb
f83c374e9725be09ed382e6fa3233054de4d71d0 28855354 corfu-server_0.1+913_all.deb
d240d0ababb5d620fc826b5527d8044a7809c490 28855232 corfu-server_0.1+916_all.deb
d8dd22edb08e3facc934d6553c4fed19e2db53b4 28855854 corfu-server_0.1+919_all.deb
fcb0bd286d5b4a507dd06eda331a6e4836537541 28856828 corfu-server_0.1+922_all.deb
aa1238014d5dcccf4bea819084e8abbfc5d1d0b7 28856832 corfu-server_0.1+924_all.deb
d57d1c49618e68917b19562613caeb74726193ae 28856882 corfu-server_0.1+926_all.deb
4fb71c679d58aa345150a5e67a2c2ecd999d7be1 28856900 corfu-server_0.1+931_all.deb
5a01a46051530fd2e3ef5dd6519172b80155292c 28857338 corfu-server_0.1+935_all.deb
f5b5ec542ac14a8ee565a8aaeba017aeed5af5f3 28857226 corfu-server_0.1+938_all.deb
be3a27eb899a8f98b7a832649957743fcfcbbe12 28857544 corfu-server_0.1+941_all.deb
8a5d431c4f33f1608ba25c3ca0c65c16291fc3a7 28857544 corfu-server_0.1+942_all.deb
8dd7cc3b8ae7117df1d8f695865d7b7d4bff234a 28857668 corfu-server_0.1+949_all.deb
b5753d9a7ac82fb86d8ee917cdb180076dd52156 29027030 corfu-server_0.1+952_all.deb
9c29d9e22d6915d8f6b9dc68613da5143b49f65c 29040916 corfu-server_0.1+957_all.deb
0da1eeac1f0e946b60f78613167dc930907ce778 29040848 corfu-server_0.1+960_all.deb
68de503fbc16c494e3e91c04b2996c248bc4eecb 29041054 corfu-server_0.1+963_all.deb
db8d3d4fd97096f8070ee4c8bc558fd96d78cc34 29041062 corfu-server_0.1+965_all.deb
50c6a80ffc8de8f387b018bd76dd9354c1648d1d 29041104 corfu-server_0.1+967_all.deb
40272f41b2ce1b7afe2cdd1f8c62d216a51576e7 29040850 corfu-server_0.1+974_all.deb
d97bf3195a6e0bf450f8c31c3bc77a2f0ad8e202 29045156 corfu-server_0.1+977_all.deb
dd91208a7b107eeeb9f7d4866a8829ad264b922c 29040974 corfu-server_0.1+979_all.deb
971b0d5d9f47268b6530a3ba47bc8e63d0524f47 29045672 corfu-server_0.1+983_all.deb
1c37bdf027aafb320bb192e97eb57eee5d5a76c1 29045728 corfu-server_0.1+988_all.deb
ea75e1f6cfb4cfc8b6ad4fe151189334d2f00027 29051550 corfu-server_0.1+992_all.deb
60d2406c3970e05ae467fd6cb6b9f4ce1907dedd 29050474 corfu-server_0.1+993_all.deb
f4ec7b56226514735c768d845bf1883b35f9f33b 8108104 corfudb-0.1-20150819.031545-1.jar
8bc9ca832fd6aca455f0afcd079a39bbc4500e8c 8108104 corfudb-0.1-20150819.044041-1.jar
a76f196c0c94fac8ec0c8b7d67e2ad3573d85d96 11989988 gemfire-binding-0.1.4.jar
896d31fa170bcb254acfd81351444d4c92d5299b 32843041 hbase-binding-0.1.4.jar
0300eaf6067112a755f164b11047b5f7da418321 27641087 infinispan-binding-0.1.4.jar
208eac214e4e8c8bcde952a32643b802d0e37574 7014493 jdbc-binding-0.1.4.jar
37d86f9c7ed1454ba163937ca873be440400d73c 4709132 mapkeeper-binding-0.1.4.jar
815c6b53cb892793c54fa0d11af2932d61d605f1 4821946 voldemort-binding-0.1.4.jar

**Comment by no2chem** [comment]
Hm, this pull request references master though. Shouldn't pruning the binaries only involve the mvn-repo or debian branches?

**Comment by Maithem** [comment]
@no2chem I created a pull request for the wrong branch.

Btw, I don't think you can prune those .debs through the github interface.
I don't think you're allowed force a push that rewrites history from the UI.

**Comment by dahliamalkhi** [comment]
git --single-branch (optionally --depth d) does the trick for now; then individual branch tracking may be added judiciously. 

But long term, we should serve binaries from elsewhere, as already discussed.

**Pull request closed without merging**
