### PR TITLE
Fixes an issue with hole filling under certain conditions

### PR DESCRIPTION
**Pull request by no2chem**
If a large hole is left in the log, hole filling sometimes does not take place due to a bug in the implementation of hole filling policy.
This patch relies on ExponentialBackoffRetry to apply the hole right away.

In addition, we add trace messages to improve debugging.

[Review on Reviewable](https://reviewable.io/reviews/corfudb/corfudb/63)

### CODE REVIEW

**Comment by medhavidhawan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[src/main/java/org/corfudb/runtime/entries/IStreamEntry.java, line 63 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/63#-K2nh56ksplJz_WZTVRe)** ([raw file](https://github.com/corfudb/corfudb/blob/9ac3810fbb0b38e8e902d7ba01283074f3bc60c0/src/main/java/org/corfudb/runtime/entries/IStreamEntry.java#L63)):</sup>
Comments on what code is.


---

<sup>**[src/main/java/org/corfudb/runtime/smr/HoleFillingPolicy/TimeoutHoleFillPolicy.java, line 1 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/63#-K2nm6oOpHcM17Ijl6pc)** ([raw file](https://github.com/corfudb/corfudb/blob/9ac3810fbb0b38e8e902d7ba01283074f3bc60c0/src/main/java/org/corfudb/runtime/smr/HoleFillingPolicy/TimeoutHoleFillPolicy.java#L1)):</sup>
File not being used: Please remove it.


---

<sup>**[src/main/java/org/corfudb/runtime/smr/SimpleSMREngine.java, line 187 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/63#-K2nmPk3Y3CFL-cL6S_Z)** ([raw file](https://github.com/corfudb/corfudb/blob/9ac3810fbb0b38e8e902d7ba01283074f3bc60c0/src/main/java/org/corfudb/runtime/smr/SimpleSMREngine.java#L187)):</sup>
remove this commented code as well.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/63)

**Comment by medhavidhawan** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/63)

**Comment by no2chem** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[src/main/java/org/corfudb/runtime/smr/HoleFillingPolicy/TimeoutHoleFillPolicy.java, line 1 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/63#-K2nm6oOpHcM17Ijl6pc)** ([raw file](https://github.com/corfudb/corfudb/blob/9ac3810fbb0b38e8e902d7ba01283074f3bc60c0/src/main/java/org/corfudb/runtime/smr/HoleFillingPolicy/TimeoutHoleFillPolicy.java#L1)):</sup>
Turns out it's still being used by other code so we should keep it for the time being.


---

<sup>**[src/main/java/org/corfudb/runtime/smr/SimpleSMREngine.java, line 187 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/63#-K2nmPk3Y3CFL-cL6S_Z)** ([raw file](https://github.com/corfudb/corfudb/blob/9ac3810fbb0b38e8e902d7ba01283074f3bc60c0/src/main/java/org/corfudb/runtime/smr/SimpleSMREngine.java#L187)):</sup>
fixed in r2.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/63)

**Comment by medhavidhawan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/63)

**Pull request merged**
