### PR TITLE
Layout builder. Refactoring.

### PR DESCRIPTION
**Pull request by zalokhan**
Renaming LayoutWorkflowManager to LayoutBuilder.
LayoutBuilder Functionality:
Modifies the layout to add or remove servers.
Throws layout modification exception if an invalid change is attempted (eg. remove all sequencers, or all layout servers)

Adding methods to add new layout, sequencer and logunit servers to the layout.

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **5b38525**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #979 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/y1qZUVykjY8jYkgxQnC0YWmdr8dWUbW8)

**Comment by zalokhan** [comment]
@Maithem Just wondering if LayoutView is the right place for this.
There are a lot of other dependencies which the ManagementServer currently takes care of. For example: 
- building and checking the validity of the new layout
- Sealing all the components before running consensus.
- while running paxos the management server keeps a track of the highest rank proposed so that the request does not get outranked

**Comment by Maithem** [comment]
Maybe that's not the right place to put it. All I was saying was the code that writes to the data store and uses information from the data store is conflated. There should be clear boundaries. For example, all layout manipulation operations use the "Layout Datastore". That data store should have clear APIs. The "LayoutManager" will use the Layout Datastore to maintain the cluster.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **ba2808e**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #979 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/tuu6yaApbDdzHjSlUWjO2Ry46UJ7phSM)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **2d45133**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #979 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/mCbo2GeAjC7PTYcDNhv3wMZtqR1zZChg)

**Comment by zalokhan** [comment]
These changes are incorporated in #970

**Pull request closed without merging**
