### PR TITLE
more concurrency tests.. passing.

### PR DESCRIPTION
**Pull request by dahliamalkhi**
this branch incorporates the test introduced by @vjeko in #488, slightly cleaning it to match Corfu test style; and a couple more concurrency-test variations.

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **cc765ff**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #501 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/Dav4k5NPNJAQdThk9gt5KFBaX99Xx54Q)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **85b3ea8**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #501 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/6catHFxwKQiA0NqweKZwjE5RxDHqg4wT)

**Comment by slfritchie** [comment]
@dahliamalkhi I've noticed a couple of things about the `MapsAsMQs` test class

1. It doesn't end with `Test`, so it isn't being run as part of `mvn test`.  Was it your intention to run the test regularly?  If yes, then it isn't happening.

2. I see the `useMapsAsMQs` test failing intermittently, perhaps 1 of 5 or 1 of 10 times.  An attached debugger says that at least one thread is stuck in the loop at https://github.com/CorfuDB/CorfuDB/blob/85efa13835cdaa4075a49cf201539300ec941d71/test/src/test/java/org/corfudb/runtime/concurrent/MapsAsMQs.java#L79

**Comment by slfritchie** [comment]
@dahliamalkhi Also, the `StreamSeekAtomicity` class has the same missing `Test` suffix.  Is that intentional?

**Pull request merged**
