### PR TITLE
Exclude Generated Code From Checkstyle

### PR DESCRIPTION
**Pull request by Maithem**
## Overview
mvn clean install is failing on checkstyle checks for auto-generated code. This PR excludes generated code from style checks. 

[ERROR] /home/box/CorfuDB/test/target/generated-sources/org/corfudb/runtime/CorfuStoreMetadata.java:2913:15: '29' is a magic number. [MagicNumber]
[ERROR] /home/box/CorfuDB/test/target/generated-sources/org/corfudb/runtime/CorfuStoreMetadata.java:3529:45: '3' is a magic number. [MagicNumber]
[ERROR] /home/box/CorfuDB/test/target/generated-sources/org/corfudb/runtime/CorfuStoreMetadata.java:3535:45: '4' is a magic number. [MagicNumber]

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

**Comment by Maithem** [comment]
Need some more reviews here please.

**Comment by Maithem** [comment]
@xnull thanks! :)

**Comment by Maithem** [comment]
@xnull can you please trigger injection-framework Expected on your vm?

**Comment by xnull** [comment]
image

**Comment by Maithem** [comment]
@xnull thanks, let me investigate

**Pull request merged**
