### PR TITLE
Performance Client Module + Utils

### PR DESCRIPTION
**Pull request by Maithem**
## Overview
Added a module to facilitate performance testing. 

Why should this be merged: Will be used for regression tests.

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

**Comment by xnull** [comment]
What motivation for having this module if we already have a ["universe"+"jmh" benchmark module](https://github.com/CorfuDB/corfudb-tests/blob/master/benchmarks/src/jmh/java/org/corfudb/benchmarks/cluster/ClusterBenchmark.java)

which can deploy and test the performance of a VM, docker and/or process cluster of Corfu

**Comment by Maithem** [comment]
> What motivation for having this module if we already have a ["universe"+"jmh" benchmark module](https://github.com/CorfuDB/corfudb-tests/blob/master/benchmarks/src/jmh/java/org/corfudb/benchmarks/cluster/ClusterBenchmark.java)
> 
> which can deploy and test the performance of a VM, docker and/or process cluster of Corfu

`jmh` is a  `microbenchmark` tool, that's only one aspect of performance testing.  You can read about the objectives of a microbenchmark here https://stackoverflow.com/questions/2842695/what-is-microbenchmarking

You've might have noticed that in jmh you cant specify that number of times a method is executed within an iteration for throughput mode. That's because that number is derived from the iteration time period to improve the sampling quality. For example, one can ask how fast can 100 threads write a billion writes to the system and we wouldn't be able to do it on jmh, or more accurately, it's not designed to provide data for those types of questions.

This module will provide tests that simulate various types of workloads to measure end-to-end performance.

**Comment by xnull** [comment]
>You can read about the objectives of a microbenchmark here 

If you take a look at a [ClusterBenchmark](https://github.com/CorfuDB/corfudb-tests/blob/master/benchmarks/src/jmh/java/org/corfudb/benchmarks/cluster/ClusterBenchmark.java) you will see that JMH successfully used not only for micro benchmarking, it works well, powerful and flexible solution and can be used in many cases despite of "micro" in its name

>You've might have noticed that in jmh you cant specify that number of times a method is executed within an iteration for throughput mode.

why not? you can execute as many methods as many times as you want within an iteration, nothing prevents from that.

> one can ask how fast can 100 threads write a billion writes to the system and we wouldn't be able to do it on jmh
if your 100 threads write 1k operations per second, guess how much time it takes to write 1 billion records?

I personally don't see why JMH is not enough in our case, your arguments not clear to me, all the cases could be easily run and covered.

**Comment by xnull** [comment]
> `jmh` is a `microbenchmarking` tool and that's only one aspect of performance testing.

Btw, https://openjdk.java.net/projects/code-tools/jmh/
>>JMH is a Java harness for building, running, and analysing nano/micro/milli/macro benchmarks written in Java and other languages targetting the JVM.

**Pull request closed without merging**
