### PR TITLE
Handling transient node failure by management server

### LINKED ISSUE #491: Failure Detector needs to reseal slow servers
The seal today only seals a majority of servers:
- Majority of layout servers
- Log units:
  - Chain: All servers
  - Quorum: Majority of servers

From above we see that we do not validate the sealing of the sequencer server.
Consider the following scenario:
```
Layout : {
  LayoutServers : { X, Y }
  SequencerServers : {Z}
  LogUnitServers : {X, Y}
  Epoch : 1
```

We now seal such that X and Y move to epoch 2 but the message never reaches Z. This is considered as a successful seal and the cluster moves ahead with the following layout.
```
Layout : {
  LayoutServers : { X, Y }
  SequencerServers : {Z}
  LogUnitServers : {X, Y}
  Epoch : 2
```

The clients now get stuck while requesting for a token as the `TOKEN_REQ` message is epoch aware and the router would invalidate this sending back a WrongEpochException (SequencerServer node's NettyServerRouter has epoch 1.)

Thus we need to identify these "out of phase" servers and correct the epoch by resealing the servers. (only seal is required. no paxos needed.)

### PR DESCRIPTION
**Pull request by zalokhan**
## Partial Seal Bug Fix

Fixes #491 

Consider the following scenario:
3 Servers
SERVER_0, 
SERVER_1,
SERVER_2
Log Unit Servers (quorum replicated): SERVER_0, SERVER_1, SERVER_2
For convenience assume that only SERVER_0 manages and corrects failures.

SERVER_2 stops responding. SERVER_0 detects this and attempts to seal the current layout and mark the failed node unresponsive.
During seal we are able to seal SERVER_0. Seal for SERVER & SERVER_2 fails. A seal failure causes the Management server to retry polling and check if failures are still present.

Now all the three servers are up and running. (SERVER_0, SERVER_1 and SERVER_2)
When the management server polls again it does not see the failure.
The data path is now blocked as SERVER_0 has been sealed while the others are not.

To correct this issue we make the `PING` message epochAware. This allows us to detect partial seals and correct them.

#### Layout Seal Tests
Corrected aggressive timeouts. Reduced test running time from 20 to 2 secs.
#### PeriodicPollingPolicy
Removed setting timeouts. The routers will rely on their default timeouts.

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **878dd0e**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #487 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/TUv67JTGjKgXIaWP3A6Zc5OY5kpk65r7)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **b608e89**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #487 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/9SMjegKRGl9azb4RkLxD3ZN5fyKWTcqR)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **1eb2fe7**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #487 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/CL4PSJCVSVUBmFz5D2oHL0vRYVWn0MKL)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **c137cff**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #487 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/8IJi7MWSSi8P6reoJu5cBpVU8M5F9P3I)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **e311da1**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #487 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/5ZTkqfj6EbzWrvNoNSUlmgH5N3h1U17W)

**Comment by zalokhan** [comment]
@slfritchie Makes sense. Ill make the change.

**Comment by zalokhan** [comment]
@slfritchie Makes sense. I've made the change.
Apart from this I've cleaned up the management server code by returning a report from the polling policy. This I feel is cleaner than the simple map we had.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **f8d1edd**.

*** 100.0% transaction FAILURE rate for 1 threads, CorfuMemoryNode mode
*** 100.0% transaction FAILURE rate for 5 threads, CorfuMemoryNode mode
*** 100.0% transaction FAILURE rate for 10 threads, CorfuMemoryNode mode
*** 100.0% transaction FAILURE rate for 1 threads, CorfuDiskNode mode
*** 100.0% transaction FAILURE rate for 5 threads, CorfuDiskNode mode
*** 100.0% transaction FAILURE rate for 10 threads, CorfuDiskNode mode

An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #487 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/iDrws2yVm6bdwpZVOeKpk0HbZS8bpVTo)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **4a3225e**.

*** 100.0% transaction FAILURE rate for 5 threads, CorfuDiskNode mode

An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #487 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/0ZdBUP1P7oO6Vvj59Ew70BmSD9Y35zNj)

**Comment by slfritchie** [comment]
Hi, Zeeshan, sorry I let NSDI interfere with reviews.

**Pull request merged**
