### PR TITLE
Merging changes into paxos branch

### PR DESCRIPTION
**Pull request by medhavidhawan**
This change is [Reviewable](https://reviewable.io/reviews/corfudb/corfudb/197)

### CODE REVIEW

**Comment by no2chem** [comment]
I'm trying to merge this change in, but I can't figure out why this PR includes a bunch of other changes from other PRs...?

**Comment by no2chem** [comment]
I'd like to close this request, but you need to provide a description of what this change does.

**Comment by slfritchie** [comment]
Is this PR backward?  "... into paxos-branch from master"

**Comment by no2chem** [comment]
It appears this pull request was made in error, closing.

**Pull request closed without merging**
