### PR TITLE
Layouts

### PR DESCRIPTION
**Pull request by dahliamalkhi**
[Review on Reviewable](https://reviewable.io/reviews/corfudb/corfudb/67)

### CODE REVIEW

**Comment by no2chem** [comment]
Reviewed 43 of 84 files at r1, 27 of 31 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

_[src/main/java/org/corfudb/infrastructure/ConfigMasterServer.txt, line 22 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U30Iu6kbkj551PcTw:-K3U30Iu6kbkj551PcTx:-362780120) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/infrastructure/ConfigMasterServer.txt#L22)):_
In general, why is this now a text file? It needs to be deleted...

---

_[src/main/java/org/corfudb/infrastructure/NettyLayoutKeeper.java, line 50 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U3E4C5Xfz_7xSwpqw:-K3U3E4C5Xfz_7xSwpqx:254156514) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/infrastructure/NettyLayoutKeeper.java#L50)):_
Please switch to @Slf4j annotation

---

_[src/main/java/org/corfudb/infrastructure/NettyLayoutKeeper.java, line 69 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U3W0aHXJCuypK7sBC:-K3U3W0aHXJCuypK7sBD:-1458497981) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/infrastructure/NettyLayoutKeeper.java#L69)):_
Probably should be a trace or debug level message

---

_[src/main/java/org/corfudb/infrastructure/NettyLayoutKeeper.java, line 121 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U3e5Iw_L4gVLQRgt5:-K3U3e5Iw_L4gVLQRgt6:-1267419428) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/infrastructure/NettyLayoutKeeper.java#L121)):_
Why is the 300ms delay necessary?

---

_[src/main/java/org/corfudb/infrastructure/wireprotocol/NettyLayoutConfigMsg.java, line 25 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U4KJ7o8Hdx2PNFirk:-K3U4KJ7o8Hdx2PNFirl:-1786114148) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/infrastructure/wireprotocol/NettyLayoutConfigMsg.java#L25)):_
I feel that while it's okay to have the standardized representation be a JSON object,
probably the objects being passed around don't need to be JSON objects but should represent the actual deserialized form..

---

_[src/main/java/org/corfudb/runtime/CorfuDBRuntime.txt, line 18 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U4pv7R89r_Tu5IXwe:-K3U4pv7R89r_Tu5IXwf:-1641525336) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/runtime/CorfuDBRuntime.txt#L18)):_
Again, why is this a text file? We should just delete it if it's not longer necessary.

---

_[src/main/java/org/corfudb/runtime/protocols/configmasters/MemoryConfigMasterProtocol.txt, line 4 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U51bW5LsS4RalWkZ1:-K3U51bW5LsS4RalWkZ2:-1961983344) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/runtime/protocols/configmasters/MemoryConfigMasterProtocol.txt#L4)):_
Delete....

---

_[src/main/java/org/corfudb/runtime/view/IViewJanitor.java, line 3 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U5TcC244MOmxrOhML:-K3U5TcC244MOmxrOhMM:-2124964431) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/runtime/view/IViewJanitor.java#L3)):_
need to fix these leftover merge messages

---

_[src/main/java/org/corfudb/runtime/view/RemoteLogView.txt, line 4 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U5f8q1RD8zp5LI2Ky:-K3U5f8q1RD8zp5LI2Kz:1713865935) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/runtime/view/RemoteLogView.txt#L4)):_
File needs to be deleted...

---

_[src/main/java/org/corfudb/runtime/view/Sequencer.txt, line 5 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U5hzjahD-WNcQN-uz:-K3U5hzjahD-WNcQN-v-:767994206) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/runtime/view/Sequencer.txt#L5)):_
Delete...

---

_[src/test/java/org/corfudb/runtime/CorfuDBRuntimeIT.java, line 11 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U6ABvQadNTl27gIYn:-K3U6ABvQadNTl27gIYo:-988233418) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/test/java/org/corfudb/runtime/CorfuDBRuntimeIT.java#L11)):_
Cleanup merge text..

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/67)_

**Comment by dahliamalkhi** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

_[src/main/java/org/corfudb/infrastructure/ConfigMasterServer.txt, line 22 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U30Iu6kbkj551PcTw:-K3VPh4wD2E_1lM1dCml:1147734176) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/infrastructure/ConfigMasterServer.txt#L22)):_
Yes, I left a bunch of .txt files for convenience (to compare, etc.). I'll remove them.

---

_[src/main/java/org/corfudb/infrastructure/NettyLayoutKeeper.java, line 121 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U3e5Iw_L4gVLQRgt5:-K3VQVLH3gmArYqmCqzH:-1744689112) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/infrastructure/NettyLayoutKeeper.java#L121)):_
generally, reconfiguration decisions must be formed one at a time, because each configuration takes only one decision (the next decision is driven by the next configuration, but you don't know what it is, until you decide). 

If the first layout server of a configuration is asked for multiple changes, and it already started handling one, it should wait until it is completed before handling the next one.

---

_[src/main/java/org/corfudb/infrastructure/wireprotocol/NettyLayoutConfigMsg.java, line 25 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U4KJ7o8Hdx2PNFirk:-K3VQxnCBbqOS1rFD0M9:1353770373) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/infrastructure/wireprotocol/NettyLayoutConfigMsg.java#L25)):_
what do you mean by "passed around"?

---

_[src/main/java/org/corfudb/runtime/view/IViewJanitor.java, line 3 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U5TcC244MOmxrOhML:-K3VREgXfEtYbRWoIGfB:903302240) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/runtime/view/IViewJanitor.java#L3)):_
how do I do it? the commit on my dir doesn't contain them :( ...

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/67)_

**Comment by no2chem** [comment]
*[src/main/java/org/corfudb/runtime/view/IViewJanitor.java, line 3 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U5TcC244MOmxrOhML:-K4UIp7UrcxFdQ5-YjMF:1491065687) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/runtime/view/IViewJanitor.java#L3)):*
Try repulling to the latest on this branch?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/67)*

**Comment by no2chem** [comment]
*[src/main/java/org/corfudb/infrastructure/wireprotocol/NettyLayoutConfigMsg.java, line 25 \[r2\]](https://reviewable.io:443/reviews/corfudb/corfudb/67#-K3U4KJ7o8Hdx2PNFirk:-K4UItrOvq-u-kzf2Pfh:1456516202) ([raw file](https://github.com/corfudb/corfudb/blob/6d7b26dac5049e9c7361cd0052e2a590270f2231/src/main/java/org/corfudb/infrastructure/wireprotocol/NettyLayoutConfigMsg.java#L25)):*
As in used in the code, since it's somewhat inconvenient to access a JSON object.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/67)*

**Pull request closed without merging**
