### PR TITLE
Add a clojure-based shell

### PR DESCRIPTION
**Pull request by no2chem**
This pull request adds a clojure-based shell, which
provides programmers with a flexible and interactive 
way to interact with Corfu.

---

This change is [Reviewable](https://reviewable.io/reviews/corfudb/corfudb/244)

### CODE REVIEW

**Comment by slfritchie** [comment]
I finally had time yesterday afternoon to start review of this PR and start experimenting, sorry about the delay.  My comments so far.

1. The shell is extremely brittle.  A single error aborts the shell.

    % bin/corfu_shell
    [...]
    org.corfudb.shell=> (x)
    CompilerException java.lang.RuntimeException: Unable to resolve symbol: x in this context, compiling:(NO_SOURCE_PATH:1:1) 
    % echo oops, here is my login shell

With the same input and error, the `clj` shell remains running and gives you another Clojure shell prompt.  I haven't investigated yet the cause of this, but it's very frustrating for casual use & exploration as-is.

    % clj
    Clojure 1.7.0
    user=> (x)
    CompilerException java.lang.RuntimeException: Unable to resolve symbol: x in this context, compiling:(NO_SOURCE_PATH:1:1)
    user=> (y)
    CompilerException java.lang.RuntimeException: Unable to resolve symbol: y in this context, compiling:(NO_SOURCE_PATH:2:1)
    user=> ^D
    %

2. It isn't clear to me how difficult it will be to parse the s-expr output from Clojure on the QuickCheck side of the world.  It ought to be "easy" because s-exprs are easy.  But the stuff inside them, like this:

    org.corfudb.shell=> (get-runtime "localhost:8000")
 
... is rendered like this:
 
    #object[org.corfudb.runtime.CorfuRuntime 0x2b2adab4 org.corfudb.runtime.CorfuRuntime@2b2adab4"]

... and parsing that and whatever other object-to-text renderings the shell decides to use may pose some significant problems?  I have no estimate of that effort yet, sorry.  Worst case would involve writing a lot of try/catch wrappers to avoid any messy data types leaking out into the shell?  That style of construction is the same scheme that I'm using now.  The only flexibility it gives is that I can write all that try/catch wrapper stuff in Clojure or in Java.

**Comment by no2chem** [comment]
The issue with the single arg, which I mentioned during the meeting, has been resolved in 2df8918.

If you read from the shell, *1, *2, *3 gives you the last returned object. *r gives you the last runtime. *e gives you the last exception.

Please read:
http://clojure.org/reference/java_interop 

You can access any Java field from the shell, so you shouldn't have to parse text. Furthermore, you should be able to connect to the REPL via a socket, which should obviate stdout parsing. For instance, to get the maxCacheSize field, you run:

org.corfudb.shell=> (.maxCacheSize *r)
100000000

You can also change any field that you want from the shell.

**Comment by slfritchie** [comment]
I still crashes with that commit.

    % git log | head -3
    commit 2df89180b00c16b4f406e3b68384c36a1a2b3ce3
    Author: Michael Wei <mwei@cs.ucsd.edu>
    Date:   Tue Oct 25 12:34:12 2016 -0700
    % mvn install >& RUNLOG ; echo $status
    0
    % bin/shell
    WARNING: cat already refers to: #'clojure.core/cat in namespace: net.cgrand.parsley.fold, being replaced by: #'net.cgrand.parsley.fold/cat
    Welcome to the Corfu Shell
    This shell is running on Clojure 1.8.0
    All Clojure commands are valid commands in this shell.
    Commands you might find helpful:
     (get-runtime "<connection-string>") - Obtains a CorfuRuntime.
     (get-router "<endpoint-name>") - Obtains a router, to interact with a Corfu server.
     (help [<object>]) - Get the names of methods you can invoke on objects,
                         Or just gives general help if no arguments are passed.
     (quit) - Exits the shell.
    
    The special variables *1, *2 and *3 hold results of commands, and *e holds the last exception.
    The variable *r holds the last runtime obtrained, and *o holds the last router obtained.
    
    org.corfudb.shell=> (x)
    CompilerException java.lang.RuntimeException: Unable to resolve symbol: x in this context, compiling:(NO_SOURCE_PATH:1:1) 
    %

**Comment by no2chem** [comment]
Sorry, didn't push the don't exit on exception commit (	c714be0).

Should not exit on an exception in interactive mode anymore.

**Comment by slfritchie** [comment]
The commits from Saturday (now vanished in the latest rebase & force push) fixed the broken QuickCheck tests.  +1 to all else.

Suggestions for improvement, since we're all Clojure newbies.  Except
for Michael, who's now written far more Clojure code in this PR than I
have to date.  `^_^`

IMO, all are outside of the scope of this PR.

* Parseability & consistency of the script output.  The ACK/NACK
  output of the old cmdlet scripts was not well-planned.  I took a
  small step forward when I changed the cmdlet interface's return
  value from `void` to `String[]`.  Then the output was prefixed with
  "OK" or "ERROR".  But the scheme wasn't fully baked in design or
  implementation.  If we want the output of these scripts to be useful
  to non-human consumers, we should consider something better.

* Exit status codes appear to be missing in the new scripts.  Again,
  for non-human consumption, the exit status code is useful.

* Eventually, we'll likely want to move some function definitions
  outside of individual CLI scripts into a more easily accessible
  collection.

**Pull request merged**
