### PR TITLE
Richer stream seek interface and cleaned up version lock object

### PR DESCRIPTION
**Pull request by no2chem**
This patch reopens a set of changes introduced in #474 and #492.

In addition to the changes previously introduced, this
set addresses some concurrency bugs and removes the exposure
of external lock interfaces from versionLockedObject. It
also merges a change introduced by @dmalkhi which fixes a
correctness bug related to hole filling and false aborts
during transactions.

This patch also reduces the default aggressive hole-filling
behavior. Empty reads are no longer cached, so reads of
unwritten entries must go back to the logging unit. The
default hole retry rate has been increased to 10, but the
test framework sets this parameter to 0 in order to 
stress any concurrency corner cases which may be present.

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **d3c858a**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #499 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/aniHXyMtPvpxjdH00W3CcJmbJzzg7ZD2)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **5448810**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #499 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/hNLMyih7RYmEAR78W367PXX0BmFC1Oi6)

**Comment by no2chem** [comment]
Most recently, I added bulk reads from the stream layer into this branch. This batches reads to the address space layer, improving performance.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **2641127**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #499 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/QaUeuRWfNqiU29UsDxAY18MK8DUb32t7)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **86019e7**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #499 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/dSTJFAtJ7CEfqNk9Hc8FN5Unuryv45tK)

**Pull request merged**
