### PR TITLE
Fix buffer release during exceptions

### LINKED ISSUE #103: buffer leak
Looking at the server, I see: NettyServerRouter.channelRead().  Looks like there are cases where we don't free the netty buffer?  For example, handler=null, not a valid Epoch and in general, any exception.  According to netty docs, we should be releasing the netty buffer.

### PR DESCRIPTION
**Pull request by no2chem**
Fixes #103, which is an issue with buffers being released during exceptions.

---
This change is [Reviewable](https://reviewable.io/reviews/corfudb/corfudb/104)

### CODE REVIEW

**Comment by no2chem** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/104)*

**Comment by medhavidhawan** [comment]
*[src/main/java/org/corfudb/infrastructure/NettyServerRouter.java, line 123 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/104#-KCzk1QLpKuaoz3mGrkj:-KCzk1QLpKuaoz3mGrkk:-1810892714) ([raw file](https://github.com/corfudb/corfudb/blob/376c15fbccf30668758d9779bddce036b7cddd29/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java#L123)):*
I think in the catch block

     ((CorfuMsg)msg).release();

would have done the trick as well. The null check is redundant and the handled check becomes unnecessary in the exception block.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/104)*

**Comment by medhavidhawan** [comment]
*[src/main/java/org/corfudb/infrastructure/NettyServerRouter.java, line 123 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/104#-KCzk1QLpKuaoz3mGrkj:-KCzliiTCsM620ubVgod:-575138106) ([raw file](https://github.com/corfudb/corfudb/blob/376c15fbccf30668758d9779bddce036b7cddd29/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java#L123)):*
Oh I see CorfuMsg can be null as well. maybe null check is still needed then. Can a CorfuMsg be null. Does the netty pipeline do that ? I forget that now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/104)*

**Comment by no2chem** [comment]
*[src/main/java/org/corfudb/infrastructure/NettyServerRouter.java, line 123 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/104#-KCzk1QLpKuaoz3mGrkj:-KD-b-oqFRvWdfWXKKlJ:1526067013) ([raw file](https://github.com/corfudb/corfudb/blob/376c15fbccf30668758d9779bddce036b7cddd29/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java#L123)):*
I think its possible for a message to come down the pipeline null if the Deserializer fails somehow to deserialize it. It actually throws an exception, but I'm not sure if that results in channelRead getting a message.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/104)*

**Comment by medhavidhawan** [comment]
*[src/main/java/org/corfudb/infrastructure/NettyServerRouter.java, line 123 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/104#-KCzk1QLpKuaoz3mGrkj:-KD-jCmJt3NDlU-f8rR6:1235680641) ([raw file](https://github.com/corfudb/corfudb/blob/376c15fbccf30668758d9779bddce036b7cddd29/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java#L123)):*
ok cool. I think your code is better as it does release for the runtime exception case as well. I do not know where that runtime exception is handled though ? This code piece only handles exception.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/corfudb/corfudb/104)*

**Pull request merged**
