### PR TITLE
Run universe tests in parallel on travis

### PR DESCRIPTION
**Pull request by xnull**
## Overview

Description:

Why should this be merged: 

Related issue(s) (if applicable): #<number>

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

**Comment by WenbinZhu** [comment]
Looks like travis is still taking 25 min to run universe tests, not taking advantage of parallelism ?

**Comment by hisundar** [comment]
This test
`NodeUpAndPartitionedIT.nodeUpAndPartitionedTest:48>lambda$nodeUpAndPartitionedTest$2:58->lambda$null$1:115 » UnreachableCluster`
fails quite often, can we perhaps fix that too?

**Comment by xnull** [comment]
@WenbinZhu it should reduce time to ~15 min. Let me figure out why this change doesn't reduce time

**Comment by xnull** [comment]
Takes same time as a sequential version

**Pull request closed without merging**
