### PR TITLE
Fix for #292: add 'n' option to 1-line usage summary

### LINKED ISSUE #292: No default value for --no-verify flag for corfu_server
The `--no-verify` flag was introduced at commit 0b416e33eb3d9aca75043b610db2c892f0c2d3a4.  If the flag is not specified on the command line, the apparent lack of default value (in the `USAGE` string) causes a null pointer exception, and the server cannot be started.

    % ./bin/corfu_server -l /tmp/some/path -s 8000 -d WARN
    ▄████████  ▄██████▄     ▄████████    ▄████████ ███    █▄
    ███    ███ ███    ███   ███    ███   ███    ███ ███    ███
    ███    █▀  ███    ███   ███    ███   ███    █▀  ███    ███
    ███        ███    ███  ▄███▄▄▄▄██▀  ▄███▄▄▄     ███    ███
    ███        ███    ███ ▀▀███▀▀▀▀▀   ▀▀███▀▀▀     ███    ███
    ███    █▄  ███    ███ ▀███████████   ███        ███    ███
    ███    ███ ███    ███   ███    ███   ███        ███    ███
    ████████▀   ▀██████▀    ███    ███   ███        ████████▀
                            ███    ███
    Welcome to CORFU SERVER
    Version 0.1-SNAPSHOT (0b416e3)
    Serving on port 8000
    Service directory: /tmp/some/path
    objc[36537]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
    16:06:09.488 WARN  [main] o.c.i.SequencerServer - Sequencer recovery requested but checkpoint not set, defaulting to 0
     Exception in thread "main" java.lang.NullPointerException
    	at org.corfudb.infrastructure.LogUnitServer.reboot(LogUnitServer.java:301)
    	at org.corfudb.infrastructure.LogUnitServer.<init>(LogUnitServer.java:257)
    	at org.corfudb.infrastructure.CorfuServer.main(CorfuServer.java:183)

### PR DESCRIPTION
**Pull request by slfritchie**
In the "learn something new every day" department, it looks like the docopt parsing won't create a default value for a flag if that flag isn't mentioned in the 1-line summary.  Fixes #292.

### CODE REVIEW

**Comment by slfritchie** [comment]
TravisCI failures were due to an unrelated test timing problem, please ignore those CI failures.

**Comment by slfritchie** [comment]
Anyone for a thumbs-up race on a 1-liner? @Maithem @no2chem @dahliamalkhi @zalokhan @medhavidhawan?

**Comment by Maithem** [comment]
@slfritchie restarted the build, ill merge it once it passes.

**Comment by slfritchie** [comment]
This bug prevents the server from running at all if using the `-l` flag for persistent storage.  Use of the `-m` flag instead does not trigger the problem.

As far as I can tell, all JUnit tests that use `ServerContextBuilder` won't be able to test for regressions of this fix; see https://github.com/CorfuDB/CorfuDB/blob/master/src/test/java/org/corfudb/infrastructure/ServerContextBuilder.java#L33-L44

Recommendations for how to implement a JUnit friendly test would be appreciated.

**Comment by Maithem** [comment]
@slfritchie I think an integration test is appropriate here, but we don't have those types of tests right now. Coming soon.

**Pull request merged**
