### PR TITLE
Stabilize and cleanup VM harness integration, enable cluster status check

### PR DESCRIPTION
**Pull request by WenbinZhu**
## Overview

- Use endpoint to sort servers used by fault detector
- Fix sudo command issue on VM that causes commands to be lost silently
- Stabilize and cleanup VM harness integration tests
- Enable cluster status check for both docker and VM harness integration tests

Description:

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

**Comment by apavan** [comment]
LGTM - all IT code changes to fix for VM failures. Mostly imports and minor timeout changes.

**Comment by xnull** [comment]
Why this is still not merged?

**Comment by zalokhan** [comment]
@WenbinZhu Can you rebase this.

**Comment by WenbinZhu** [comment]
> @WenbinZhu Can you rebase this.

@zalokhan Done.

**Pull request merged**
