### PR TITLE
Scan & Filter for SMRMap Queries

### PR DESCRIPTION
**Pull request by annym**
- Introducing a scanAndFilter method into SMRMap which avoids the cost
  in performance when using iterators for queries over large maps.

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **691c5c7**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #625 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/s10CNQKL35Rd5UI1nAM4qpBvWdUmwmvG)

**Comment by annym** [comment]
The following dashboard shows performance results for the CorfuDB Benchmark Framework when using the introduced scanAndFilter method vs. iterators (as done on all benchmark runs so far):
[Pull Request #625 Dashboard Comparison scanAndFilter vs. Iterators](https://snapshot.raintank.io/dashboard/snapshot/el4zacXpXJH5UfSfCEFkg0pYszOY7EP3)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **64dda9a**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #625 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/GkLb3TdiCww6XbCwB18sZo74jCgKmKab)

**Comment by annym** [comment]
@no2chem actually I don't get any CME (I checked for that). But yes, I can certainly add it. Should I add it here, or in the 'ISMRMap'?

**Pull request merged**
