### PR TITLE
Boolean logic fix BackpointerStreamView.getHasNext

### PR DESCRIPTION
**Pull request by vjeko**
Return true if readQueue is not empty.

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **75c22fa**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #626 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/qVsih1ZlIk56sIpfYygPeeJ4CcP6ihC4)

**Comment by kspirov** [comment]
Isn't this unit testable?

**Comment by vjeko** [comment]
OK I'll add a test.

**Comment by zalokhan** [comment]
@vjeko I've added a test and created a PR to your forked master. Once you approve, it will get added here.
This test fails on master and passes with this patch.

**Comment by vjeko** [comment]
Thanks @zalokhan !

**Pull request merged**
