### PR TITLE
Added Doxyfile

### PR DESCRIPTION
**Pull request by Maithem**
## Overview
Added Doxyfile.

Why should this be merged: Allows for easier code exploration and better illustrations of components interdependence (shown below)

image

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

**Review by zfrenette — APPROVED** [review]

**Review by achinmishra — APPROVED** [review]

**Review by pankti-m — COMMENTED** [review]
Will the diagram be generated on compilation?  Will it dynamically change with changes?  How can the tool be used?

**Comment by Maithem** [comment]
> Will the diagram be generated on compilation? Will it dynamically change with changes? How can the tool be used?

No. In order to generate the files you need to execute `doxygen`  in the root repo directory and it will parse the source code and generate a bunch of html files in `CorfuDB/docs/doxygen`. There will be an index.html file that you can open with your browser.

**Comment by annym** [comment]
> > Will the diagram be generated on compilation? Will it dynamically change with changes? How can the tool be used?
> 
> No. In order to generate the files you need to execute `doxygen` in the root repo directory and it will parse the source code and generate a bunch of html files in `CorfuDB/docs/doxygen`. There will be an index.html file that you can open with your browser.

@Maithem can we add this to the README? that way it serves as a guide for someone new to the project and maybe more people would use it...

**Comment by Maithem** [comment]
> > > Will the diagram be generated on compilation? Will it dynamically change with changes? How can the tool be used?
> > 
> > 
> > No. In order to generate the files you need to execute `doxygen` in the root repo directory and it will parse the source code and generate a bunch of html files in `CorfuDB/docs/doxygen`. There will be an index.html file that you can open with your browser.
> 
> @Maithem can we add this to the README? that way it serves as a guide for someone new to the project and maybe more people would use it...

Done.

**Pull request merged**
