### PR TITLE
Failure detector tune timeouts

### PR DESCRIPTION
**Pull request by xnull**
## Overview

Description:

Why should this be merged: 
Tune failure detector timeouts
Related issue(s) (if applicable): #<number>

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

**Comment by apavan** [comment]
LGTM

**Comment by apavan** [comment]
> Expose these through the server configs #1703
> 
> Also, change idleConnectionTimeout to 5 seconds
> https://github.com/CorfuDB/CorfuDB/blob/master/runtime/src/main/java/org/corfudb/runtime/CorfuRuntime.java#L255

Maithem,
We can push that change with Slava's link failure PR. For now we will go with this as I tested 2 times with these settings and it passed both times. Better to keep it minimal in this attempt.

**Comment by apavan** [comment]
@Maithem can you kick off Injection Framwork tests?

**Comment by Maithem** [comment]
@apavan You can make it configurable later, but you also need to change the corfu runtime parameter defaults. They actually don't make sense and will break for cold shutdown on VMs.

**Comment by apavan** [comment]
> @apavan You can make it configurable later, but you also need to change the corfu runtime parameter defaults. They actually don't make sense and will break for cold shutdown on VMs.

Let me give these setting a try and get back to you.

**Pull request merged**
