### PR TITLE
Cache Optimization

### PR DESCRIPTION
**Pull request by annym**
## Overview

Description:
     Cache improvement to reduce NoRollBackExceptions.

### CODE REVIEW

**Review by hisundar — APPROVED** [review]
LGTM

**Review by zhangn49 — APPROVED** [review]

**Review by pankti-m — APPROVED** [review]
Can you explain how this change will prevent NRE?

**Comment by Maithem** [comment]
I suspect what's happening is that the optimistic stream has entries that were added by the insert but are never applied to the VLO, because it was never synced. In this case, the VLO will try to undo the optimistic stream and fail because it cant find the undo records: there's nothing to undo, because it was never applied.

The proper fix is to ignore SMR entries from the optimistic stream that were never applied to the VLO. This change will only hide the bug in the VLO and regress the performance improvements that were introduced by the pure mutators.

**Comment by apavan** [comment]
> I suspect what's happening is that the optimistic stream has entries that were added by the insert but are never applied to the VLO, because it was never synced. In this case, the VLO will try to undo the optimistic stream and fail because it cant find the undo records: there's nothing to undo, because it was never applied.
> 
> The proper fix is to ignore SMR entries from the optimistic stream that were never applied to the VLO. This change will only hide the bug in the VLO and regress the performance improvements that were introduced by the pure mutators.

Given this is a blocker for the release, we will push this CL and then get the proper fix out as a follow up.

**Pull request merged**
