### PR TITLE
Set snapshot transaction default log address to global tail

### LINKED ISSUE #653: Snapshot transaction default log address should not be -1
During the discussion of PR #641, Dahlia and I had an email discussion.

    Me: [... I made a change to create a] snapshot txn with the
    current global log address.

    Dahlia: Well, I think this should be the default behavior for
    snapshot TX, not just for checkpoint purposes. The TXBuilder
    allows to override and specify a concrete snapshot; I suspect
    this will rarely be used. I think it got lost in refactoring
    at some point.

To make things concrete, if test code creates a snapshot transaction without specifying a log address/snapshot location:

            getDefaultRuntime().getObjectsView().TXBuild()
                    .setType(TransactionType.SNAPSHOT)
                    .begin();

... then today's code will use address -1.  No data is readable at that address, which (arguably) isn't useful.

### PR DESCRIPTION
**Pull request by slfritchie**
Fixes #653.

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **7871557**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #864 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/U169YB3OjDvfcpVv3BglOeuGsVFx1VPr)

**Comment by no2chem** [comment]
@dahliamalkhi it seems to fail some integration tests, so it still needs work.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **2fe8df0**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #864 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/WTUaWcLFn7H3ObWyNnCyGPpv3uQC9M91)

**Comment by slfritchie** [comment]
@no2chem @zalokhan I've found the quirk that was causing the unit test failures in the ServerRestartIT tests.  I've force-pushed commit 2f51a3c with the fix.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **1f494f6**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #864 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/ciBvhiqmQEp3Y5WGBlS0qSe3lK8hh2Hk)

**Comment by Maithem** [comment]
subsumed by https://github.com/CorfuDB/CorfuDB/pull/1323

**Pull request closed without merging**
