### PR TITLE
add bulk hole fill response, needed for bulk hole fill

### PR DESCRIPTION
**Pull request by zjohnny226**
Part of Issue #749

Modify the hole fill to take in a list of addresses.

LogData.HOLE has a null rank, if processed in StreamLogWithRankedAddressSpace::assertAppendPermittedUnsafe(), there would be a NullPointerException. There's no other place that throws DataOutrankedException, ValueAdoptedException.

QuorumReplicationProtocol doesn't even use this function, it just does a normal write. Why don't we have a uniform procedure for both?

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **3110ee3**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #807 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/alUYQLngH2ebWTluUMvdnQdcAFkOgBme)

**Comment by zjohnny226** [comment]
@dahliamalkhi multi-hole fill is not used by the replication protocol. However, chain replication protocol does use this server API, it's just that each request contains a list of one address.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **a6904c1**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #807 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/Qm4y6am5Wp1APVjOUgDdB6eqialKySXy)

**Comment by xnull** [comment]
outdated

**Pull request closed without merging**
