### PR TITLE
Added Support For Protobufs

### PR DESCRIPTION
**Pull request by Maithem**
Added maven hooks to generate protobuf sources.

### CODE REVIEW

**Comment by Maithem** [comment]
@no2chem  its ready now

**Comment by no2chem** [comment]
Hm, is this the best way to do it? 

In router I have:
```
            <plugin>
                <groupId>com.github.os72</groupId>
                <artifactId>protoc-jar-maven-plugin</artifactId>
                <version>3.1.0.2</version>
                <executions>
                    <execution>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <protocVersion>3.1.0</protocVersion>
                            <inputDirectories>
                                <include>src/main/protobuf</include>
                                <include>src/test/protobuf</include>
                            </inputDirectories>
                            <outputDirectory>
                                target/generated-test/sources
                            </outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
which avoids the need for apt-get of protobuf libs.

**Comment by Maithem** [comment]
I looked at that too, but its not an official repo. Other github/travis projects have the apt-get command.

**Comment by no2chem** [comment]
It's in Maven Central, so it should be fine? I'd rather avoid adding another dependency users will have to mainly acquire to compile the project. Using antrun seems a bit fragile, and using apt-get that way will lock us into non-container based builds on Travis.

**Comment by Maithem** [comment]
@no2chem  done, that turned out to be cleaner.

**Pull request merged**
