### PR TITLE
Remove edit layout cmdlet and fix ITs

### PR DESCRIPTION
**Pull request by zalokhan**
## Overview

Description: Fixing the layout cmdlets.
Removing edit layout cmdlet functionality as it has been replaced by add_node and remove_node.
Re-enabling cmdlet ITs.

Why should this be merged: Test cmdlet ITs.

Related issue(s) (if applicable): #1228 

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **f536dc9**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #1238 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/PVzgrYm5RnLBVMA2IaOWj4fM0S4qfieL)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **8d51511**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #1238 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/VrEZE90zbQEZZZehrVYmKcyiqOl25Ct5)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **b9411c7**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #1238 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/j5l9CBSDFaq5iiIAIAAje60MNeiZsPYG)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **3c65460**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #1238 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/aKak4eUgZvm8XDUqn5bZvWLbW2pbVZgW)

**Comment by annym** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity decreasing per file
==============================
+ test/src/test/java/org/corfudb/integration/AbstractIT.java  -1
         

Clones removed
==============
+ test/src/test/java/org/corfudb/integration/CmdletIT.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/CorfuDB/CorfuDB/pullRequest?prid=4653462&bid=15584353)

**Comment by annym** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity decreasing per file
==============================
+ test/src/test/java/org/corfudb/integration/AbstractIT.java  -1
         

Clones removed
==============
+ test/src/test/java/org/corfudb/integration/CmdletIT.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/annymartinez.m/CorfuDB/pullRequest?prid=4651490&bid=15577803)

**Comment by xnull** [comment]
obsolete

**Pull request closed without merging**
