### PR TITLE
Some refactoring and cleanup on the client side

### PR DESCRIPTION
**Pull request by kspirov**
Next incremental change from https://github.com/CorfuDB/CorfuDB/pull/449

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **b78c47f**.

**Throughput**: _Average_: 45.4545454545 [executions/sec], _Standard Deviation_: 19.5860044483
**Latency**: _Average_: 220.062 [ms], _Standard Deviation_: 144.303597169

 An interactive dashboard with Pull Request Performance Metrics is available at:
[Pull Request #459 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/idTGkno7tMiuc2vW03IlspOHto2M5RFy)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **b78c47f**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #459 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/NdyOlpDrqWJn9Dm0x5jwVqITLhJssn3L)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **dbed4c8**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #459 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/hIv3ln4nQaqM8ytLny3BjBv3oq2c5TBx)

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **e0ee654**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #459 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/nnbC2axU5MFLzP2f0FXCburbAalgXFDU)

**Comment by kspirov** [comment]
Uh oh - the sequencer with failover flag didn't have to be here. I will submit another small pull request to clean this up, along with the renaming of QuorumFutureFactory to QuorumFuturesFactory (recommendation of Michael)

**Pull request merged**
