### PR TITLE
Removed StreamedLogData

### PR DESCRIPTION
**Pull request by Maithem**
More code clean up.

### CODE REVIEW

**Comment by Maithem** [comment]
slfritchie We aren't , just checked

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **a6c542a**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #656 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/hHliolJX1Q3eg8yglXE7huAiHsRkRtfz)

**Comment by dahliamalkhi** [comment]
to clarify: I believe StreamedLogData -is- needed. it is an interim step. @no2chem ?

**Comment by no2chem** [comment]
@dahliamalkhi I think it's safe to remove this code from master from the time being as it may confuse anyone reading the code. We can always add it in later.

**Pull request merged**
