### PR TITLE
Console logging compression

### PR DESCRIPTION
**Pull request by xnull**
## Overview

Description:
Average compression ration for our logs is 1:20.
Change max file size to make average gzipped logs size equals 35mb.
Math:
When log file comes 700mb it gets compressed to ~35-40mb
We can have up to 30 compressed log files
Max total disk space consumed by gzipped logs: 40*30 = 1.2GB
And one, not compressed log file: 700mb.
Total number of uncompressed logs: 700 * 30 + 700 = 22GB.

Previous parameters for a total number of uncompressed logs: 100*30 + 100 = 3GB which is ~ 9 hours in a prod environment.

The diff: 22GB - 3GB = 18GB which is ~ 54 hours in a prod environment.

New settings, total time: ~70 hours. 

P.S. if we get rid of log messages:
1. `Trying connection to layout server...`
2. `log write...`

It should reduce logs about 60-80%.
Then we can count on ~ 300-500 hours of logs.

Why should this be merged: 

Related issue(s) (if applicable): #<number>

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

**Comment by zalokhan** [comment]
Your calculation is not accounting for the compaction and the wrapper logs which share the same quota.

**Comment by xnull** [comment]
>wrapper logs
pretty small, if I am not wrong we limit it by 100mb. Usually, it's 50mb

**Comment by xnull** [comment]
> compaction logs
outside of Corfu. But again if compaction logs consume more than 100mb, it means something wrong with that logs

**Comment by zalokhan** [comment]
>But again if compaction logs consume more than 100mb, it means something wrong with that logs

@xnull That is totally relative. 100MB might be too small if it can't even store 2-3 compaction runs.
You might want to check the compactor log xml configurations to know the maximum size the compactor logs can take.

**Comment by xnull** [comment]
> Is there any performance tests? Will compression significantly affect the logging performance?

I don't see how this question can be relevant. So, I am pretty sure there is no performance impact

**Comment by xnull** [comment]
> @xnull That is totally relative. 100MB might be too small if it can't even store 2-3 compaction runs.

Yes, will do, but it must not affect this change anyway

**Comment by xnull** [comment]
Are we ok with the change?

**Pull request merged**
