### PR TITLE
Syncronize LogData

### PR DESCRIPTION
**Pull request by Maithem**
Syncronize access around the data byte array.

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **55d2888**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #961 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/C5dsyGsLf4jQLQcdWC3IN6r5HbqXHI4K)

**Comment by Maithem** [comment]
@no2chem It seems like there is a race condition that's causing an NPE. Two threads can interleave while calling getPayload and getSizeEstimate such that (data != null) executes before getPayload and then return data.length is executed after getPayload, which causes an NPE to be thrown.

Trace:

java.lang.NullPointerException
        at org.corfudb.protocols.wireprotocol.LogData.getSizeEstimate(LogData.java:97) ~[runtime-0.1.0.jar:?]
        at org.corfudb.runtime.view.stream.AbstractQueuedStreamView.addToResolvedQueue(AbstractQueuedStreamView.java:64) ~[runtime-0.1.0.jar:?]
        at org.corfudb.runtime.view.stream.AbstractQueuedStreamView.getNextEntry(AbstractQueuedStreamView.java:110) ~[runtime-0.1.0.jar:?]

**Comment by no2chem** [comment]
We should avoid adding unnecessary synchronization. 
Seems like a simple fix that wouldn't require synchronization is to obtain a pointer to data as a local variable, then check if that pointer is null.

**Comment by Maithem** [comment]
@no2chem good observation, updated patch.

**Comment by no2chem** [comment]
@Maithem Ok, approve, feel free to merge once checks pass.

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **79acf1f**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #961 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/1zubAxtzsJKngW3w2fLm1gSdMgm87DCu)

**Pull request merged**
