### PR TITLE
Changed version to 0.1.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by zalokhan**
Modifying 0.1-SNAPSHOT to 0.1.1-SNAPSHOT for Corfu v0.1.1

### CODE REVIEW

**Comment by bitmingw** [comment]
@no2chem Can you help to review this change?

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **4f22268**.

*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Scan workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx+Iterator workload, 10 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 1 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 5 threads, Disk mode
*** 0.0% transaction FAILURE rate for NonConflictingTx workload, 10 threads, Disk mode
 
 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #959 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/K7FgWHNxkYPhD90bVh4Oqkx8bP7qwM6y)

**Comment by no2chem** [comment]
@zalokhan @bitmingw Last time I asked to put it in a variable so we won't have to modify it in 12 places in the future. Is that not possible?

**Comment by bitmingw** [comment]
Looks like it is not possible? https://stackoverflow.com/questions/10582054/maven-project-version-inheritance-do-i-have-to-specify-the-parent-version

**Comment by no2chem** [comment]
Cool, looks good then.

**Pull request merged**
