### PR TITLE
High priority Clients

### PR DESCRIPTION
**Pull request by Maithem**
## Overview
Porting from master

commit 5bffde3b499e2d75dcdf1d22a9e60c8cceb63ae7
Author: Maithem <Maithem@users.noreply.github.com>
Date:   Tue Jul 9 13:14:23 2019 -0700

    Add Priority Level For Clients
    
    Added the ability for clients to tag their requests with a priority
    level, this priority is then used by the servers to reject certain
    tasks under resource constraints.
    
    Added the ability to set a max size on the data log. The LogUnit
    will now track the log size and fail writes after the log size
    has been reached. Except for the case where the writes originate
    from a high priority client.
    
    Ignore QuorumReplicationProtocolTest Tests
    
    Set the priority level of the management clients to high.
    
    Log the CorfuRuntimeParameters when the client connects.
    
    readingTrimmedAddress wait for futures.
    
    refactored initStreamLogDirectory

### CODE REVIEW

**Comment by hisundar** [comment]
Can we get this one merged too please?

**Comment by Maithem** [comment]
@hisundar just updated the branch.

**Comment by Maithem** [comment]
@annym can you please retrigger the test?

**Comment by Maithem** [comment]
@annym Thanks!

**Pull request merged**
