### PR TITLE
[Merge after #1881 is re-introduced] More cleanups on deserializing logData payload

### PR DESCRIPTION
**Pull request by WenbinZhu**
## Overview

Description:

A followup on PR #1881, remove runtime dependency on two more APIs.

## Checklist (Definition of Done):

- [x] There are no TODOs left in the code
- [x] [Coding conventions](https://github.com/CorfuDB/CorfuDB/wiki/Corfu-Style-Guidelines) (e.g. for logging, unit tests) have been followed
- [x] Change is covered by automated tests
- [x] Public API has Javadoc

### CODE REVIEW

**Comment by WenbinZhu** [comment]
Merge after #1881 is re-introduced.

**Comment by Maithem** [comment]
Please resolve conflicts and rebase.

**Comment by WenbinZhu** [comment]
> Please resolve conflicts and rebase.
@Maithem I will later reintroduce #1881 and collapse this patch with it for our next production release branch.

**Comment by Maithem** [comment]
@WenbinZhu please push this through (on master), it doesn't have to be on .2.3

**Comment by WenbinZhu** [comment]
> @WenbinZhu please push this through (on master), it doesn't have to be on .2.3

@Maithem Squashed in new patch #1983

**Comment by WenbinZhu** [comment]
Superseded by #1983

**Pull request closed without merging**
