### PR TITLE
updated corfu-repos on readme

### PR DESCRIPTION
**Pull request by dahliamalkhi**
minor stylistic changes to new sequencer, and added one more unit test on it

### CODE REVIEW

**Comment by no2chem** [comment]
Did you mean to add the sequencer changes to this PR?

**Comment by dahliamalkhi** [comment]
yes. it's a minor patch + minor stylistic patches, as I wrote.

**Comment by dahliamalkhi** [comment]
addresses #283

**Comment by no2chem** [comment]
I see. Could we merge #313 first, pending review, since that also changes README.md?

**Pull request merged**
