### PR TITLE
Created and integrated Server Context

### PR DESCRIPTION
**Pull request by medhavidhawan**
* Create Server Context responsible for common Server Operations:
  - Common node level data store
  - Persistence of SERVER EPOCH
* Moved the SET_EPOCH message handler to LayoutServer.
* Created a ServerContextBuilder and changed all the tests to use it
instead of ServerConfigBuilder.

---
This change is [Reviewable](https://reviewable.io/reviews/corfudb/corfudb/210)

### CODE REVIEW

**Comment by no2chem** [comment]
*[src/main/java/org/corfudb/infrastructure/NettyServerRouter.java, line 40 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/210#-KOgs244IU9Uc0Yy8Sge:-KOgs244IU9Uc0Yy8Sgf:b5sb3j) ([raw file](https://github.com/corfudb/corfudb/blob/a8ffe01a04548341003ad1a113b08b931d9cf011/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java#L40)):*
> ```Java
>         handlerMap = new ConcurrentHashMap<>();
>         baseServer = new BaseServer();
>         this.serverContext = serverContext;
> ```

See comment above. For now, NettyServerRouter should keep its own copy of what it thinks the epoch is, and layoutServer (which has a handle to the router, should configure it. Eventually, we'll remove that as well and allow users to set a custom test condition for all messages...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/corfudb/corfudb/210)*

**Comment by no2chem** [comment]
*[src/main/java/org/corfudb/infrastructure/CorfuServer.java, line 159 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/210#-KOgriQ-iULjFMhsOG0y:-KOgriQ0d-dDWDvGhlib:b-i07vqf) ([raw file](https://github.com/corfudb/corfudb/blob/a8ffe01a04548341003ad1a113b08b931d9cf011/src/main/java/org/corfudb/infrastructure/CorfuServer.java#L159)):*
> ```Java
> 
>         // Now, we start the Netty router, and have it route to the correct port.
>         NettyServerRouter router = new NettyServerRouter(serverContext);
> ```

NettyServerRouter shouldn't need to have access to serverContext.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/corfudb/corfudb/210)*

**Comment by medhavidhawan** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/main/java/org/corfudb/infrastructure/CorfuServer.java, line 159 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/210#-KOgriQ-iULjFMhsOG0y:-KOk0L4juXHLD-Kh4GsL:bdiolhk) ([raw file](https://github.com/corfudb/corfudb/blob/a8ffe01a04548341003ad1a113b08b931d9cf011/src/main/java/org/corfudb/infrastructure/CorfuServer.java#L159)):*
<details><summary><i>Previously, no2chem (Michael Wei) wrote…</i></summary>
> NettyServerRouter shouldn't need to have access to serverContext.
</details>
ok. I added the ServerContext in the Router because the logic of set/get router was being done in 2 places ( NettyServerRouter and TestServerRouter) and I did not want the logic to diverge at any time.  LayoutServer setting the data value in the Router is doable but it might mean synchronization across classes, once I get to fixing that. Can the Server let in an older epoch message on one thread when another thread is setting the epoch on the router ? I am still thinking through that.

---

*[src/main/java/org/corfudb/infrastructure/NettyServerRouter.java, line 40 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/210#-KOgs244IU9Uc0Yy8Sge:-KOk2PmmRHdtEpbCDHHL:b-dgp1d) ([raw file](https://github.com/corfudb/corfudb/blob/a8ffe01a04548341003ad1a113b08b931d9cf011/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java#L40)):*
<details><summary><i>Previously, no2chem (Michael Wei) wrote…</i></summary>
> See comment above. For now, NettyServerRouter should keep its own copy of what it thinks the epoch is, and layoutServer (which has a handle to the router, should configure it. Eventually, we'll remove that as well and allow users to set a custom test condition for all messages...
</details>
Ok will do that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/corfudb/corfudb/210)*

**Comment by medhavidhawan** [comment]
Review status: 0 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/org/corfudb/infrastructure/CorfuServer.java, line 159 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/210#-KOgriQ-iULjFMhsOG0y:-KPPNsz_KTXhhMTRdXBs:b-4047wt) ([raw file](https://github.com/corfudb/corfudb/blob/a8ffe01a04548341003ad1a113b08b931d9cf011/src/main/java/org/corfudb/infrastructure/CorfuServer.java#L159)):*
<details><summary><i>Previously, medhavidhawan (Medhavi Dhawan) wrote…</i></summary>
> ok. I added the ServerContext in the Router because the logic of set/get router was being done in 2 places ( NettyServerRouter and TestServerRouter) and I did not want the logic to diverge at any time.  LayoutServer setting the data value in the Router is doable but it might mean synchronization across classes, once I get to fixing that. Can the Server let in an older epoch message on one thread when another thread is setting the epoch on the router ? I am still thinking through that.
</details>
I have made the changes as per your suggestion.

---

*[src/main/java/org/corfudb/infrastructure/NettyServerRouter.java, line 40 \[r1\]](https://reviewable.io:443/reviews/corfudb/corfudb/210#-KOgs244IU9Uc0Yy8Sge:-KPPO0HSbAnaY0fzbESc:bt72lw6) ([raw file](https://github.com/corfudb/corfudb/blob/a8ffe01a04548341003ad1a113b08b931d9cf011/src/main/java/org/corfudb/infrastructure/NettyServerRouter.java#L40)):*
<details><summary><i>Previously, medhavidhawan (Medhavi Dhawan) wrote…</i></summary>
> Ok will do that. 
</details>
ok made the changes please review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/corfudb/corfudb/210)*

**Comment by no2chem** [comment]
Reviewed 10 of 24 files at r1, 11 of 15 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/corfudb/corfudb/210)*

**Pull request merged**
