### PR TITLE
Avoid Scanning When Reading A Record

### PR DESCRIPTION
**Pull request by Maithem**
When a segment is opened its address space is read into memory
along with the file offsets that correspond to log entries.
As a consequence, record reads do not linearly scan the log
file anymore, instead the record is directly read from
the log file using its offset.

### CODE REVIEW

**Comment by corfudb-performance** [comment]
Results automatically generated by _CorfuDB Benchmark Framework_ to assess the performance of this pull request for commit **0a7d038**.

 An interactive dashboard with Pull Request Performance Metrics for ALL cluster types and numbers of threads in run, is available at:
 [Pull Request #484 Graphs ](https://snapshot.raintank.io/dashboard/snapshot/dVIy69woF6a4YuddsBcozjb3R0wIYAAg)

**Comment by kspirov** [comment]
This change is more correct then what I started to do. Especially the part with AddressMetadata is very good, also it good you now split the read method. I don't see any danger from this push, folks - can you merge it when you are ready, because I want to add my changes on the top of this.

@Maithem - I believe the compact() story is still not resolved here, are you OK if I take care for it?

**Comment by Maithem** [comment]
@kspirov Currently, append doesn't allow duplicates (I left it out intentionally), so compact should have the same behavior as before. Once you add your overwrite logic the compact/trim methods should be modified appropriately. 

Please go ahead, I'll review your new pull request whenever you're ready.

**Comment by kspirov** [comment]
Will do a pull request on the readOffset branch a bit later tonight.

**Pull request merged**
