### PR TITLE
Samples

### PR DESCRIPTION
**Pull request by dahliamalkhi**
add tutorials package

### CODE REVIEW

**Comment by no2chem** [comment]
Can you rebase this against master and remove the annotationProcessor branch from it? Or alternatively rebase against annotationProcessor?

**Comment by dahliamalkhi** [comment]
arghh.. I did base it off master. git playing tricks on me. argh.

**Comment by no2chem** [comment]
Rebase off master

`git rebase master`

On Thu, Nov 17, 2016 at 9:16pm, dahliamalkhi < notifications@github.com [notifications@github.com] > wrote:
arghh.. I did base it off master. git playing tricks on me. argh.

**Comment by no2chem** [comment]
you need to either delete the commits from the annotationProcessor branch, or pull onto annotationProcessor instead.

git rebase -i will let you delete the annotationPrcoessor commits.

**Pull request closed without merging**
